---
title: "descriptive analysis"
author: "Pablo Aísa"
date: "2025-03-09"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(readxl)
library(haven)
library(patchwork)
library(scales)
library(countries)
library(showtext)
library(mice)
```

## Data cleaning copied from the script

```{r}
# Religiosity-----------------------------------------------
religiosity <- read_dta("data/replication_data.dta")

religiosity <- religiosity |> 
  group_by(country_name) |> 
  slice_max(year) |> 
  ungroup()

religiosity <- religiosity |> 
  select(religiosity_percent, country_name)

religiosity <- religiosity |> 
  mutate(country = country_name(country_name, to = "simple", 
                                verbose = TRUE),
         country_iso = countrycode::countrycode(country, origin = "country.name",
                                                destination = "iso2c")) |> 
  select(country_iso, religiosity_percent)
```


```{r}
# Economic indicators---------------------------------------
economic_indicators <- read_xlsx("data/country_data.xlsx")

economic_indicators <- economic_indicators |> 
  drop_na(`Series Code`) 

economic_indicators <- economic_indicators %>%
  mutate(across(everything(), ~ str_remove_all(.x, "^\\.\\.$"))) %>%
  mutate(across(everything(), ~ if_else(.x == "", NA, .x)))

economic_indicators <- economic_indicators %>%
  mutate(latest_value = coalesce(`2023 [YR2023]`, 
                                 `2022 [YR2022]`, 
                                 `2021 [YR2021]`, 
                                 `2020 [YR2020]`)) |> 
  mutate(latest_value = as.numeric(latest_value))

economic_indicators <- economic_indicators |> 
  select(`Series Name`, `Country Name`, latest_value)

economic_indicators <- economic_indicators |> 
  pivot_wider(names_from = `Series Name`, values_from = latest_value )

economic_indicators <- economic_indicators |> 
  rename("country" = "Country Name", 
         "gini" = "Gini index",
         "gdp_pc" = "GDP per capita (constant 2015 US$)")

economic_indicators <- economic_indicators |> 
  mutate(country = country_name(country, to = "simple", 
                                verbose = TRUE),
         country_iso = countrycode::countrycode(country, origin = "country.name",
                                                destination = "iso2c")) |> 
  select(country_iso, gini, gdp_pc)
```


```{r}
# Trans laws------------------------------------------------

trans <-  read_csv("data/trans.csv")

trans <- trans |> 
  row_to_names(row_number = 1)

trans <- trans |> 
  clean_names() |> 
  select(2, 8) |> 
  drop_na(na_2) |> 
  rename("country" = "na_2")

trans <- trans |> 
  mutate(country = country_name(country, to = "simple", 
                                verbose = TRUE),
         country_iso = countrycode::countrycode(country, origin = "country.name",
                                                destination = "iso2c")) |> 
  select(country_iso, self_determination)
```


```{r}
# Rainbow score---------------------------------------------
rainbow <- read_csv("data/rainbow.csv")

rainbow <- rainbow |> 
  row_to_names(row_number = 1) |> 
  clean_names() |> 
  select(2, 3) |> 
  drop_na(na_2) |> 
  rename("country" = "na_2",
         "rain_ind" = "na_3") |> 
  mutate(rain_ind = as.numeric(rain_ind) / 100)

rainbow <- rainbow |> 
  mutate(country = country_name(country, to = "simple", 
                                verbose = TRUE),
         country_iso = countrycode::countrycode(country, origin = "country.name",
                                                destination = "iso2c")) |> 
  select(country_iso, rain_ind)

```

```{r}
survey <- read_dta("data/ZA7575.dta")

survey <- survey |> 
  select(caseid, isocntry, d10, d11, 
         d1, sd3, d7, sd1_4, sd1_7, sd1_8, d70,
         d63, qc19, d15a, d60, qc13_11, qc6_10, qc17_4)

# Recode dependent variable 
filtered_survey <- survey |> 
  mutate(trans_name = case_when(
    qc19==1 ~ 1,
    qc19==2 ~ 0,
    qc19==3 ~ NA)) 

# Recode gender
filtered_survey <- filtered_survey |> 
  mutate(female = case_when(
    d10 == 1 ~ 0,
    d10 == 2 ~ 1,
    TRUE ~ NA),
    female = factor(female))

# Recode age
filtered_survey <- filtered_survey |> 
  mutate(age = if_else(d11 == 99 , NA, d11))

# Current occupation

filtered_survey <- filtered_survey |> 
  mutate(occupation = case_when(
    d15a %in% c(1, 3) ~ "Unemployed",
    d15a == 2 ~ "Student",
    d15a == 4 ~ "Retired",
    d15a <= 9 ~ "Self employed",
    d15a <=  14 ~ "Employed" ,
    TRUE ~ NA), 
    occupation = factor(occupation))

# Recode religion 
filtered_survey <- filtered_survey |> 
  mutate(religion = case_when(
    sd3 %in% c(1, 3, 4) ~ "Christians", 
    sd3 == 2 ~ "Orthodox Chrsitian", 
    sd3 %in% c(6, 7, 8) ~ "Muslims", 
    sd3 == 5 ~ "Jewish", #he añadido judios es que me parecia raro añadir orthodox christians como una separada pero no judios pero bueno se puede cambiar
    sd3 %in% c(10, 11, 14) ~ "Other religions", 
    sd3 %in% c(12, 13) ~ "Not religious", 
    TRUE ~ NA),
    religion = factor(religion))

# Marital status

filtered_survey <- filtered_survey |> 
  mutate(marital_status = case_when(
    d7 <= 4 ~ "Married",
    d7 <= 10 ~ "Single", 
    d7 <= 12 ~ "Divorced",
    d7 <=  14 ~ "Widowed",
    d7 == 15 ~ "Other", 
    TRUE ~ NA), 
    marital_status = factor(marital_status))

# Personal satisfaction

filtered_survey <- filtered_survey |> 
  mutate(personal_satis = if_else(d70 == 5, NA, d70),
         personal_satis = case_when(
           personal_satis <= 2 ~ "Satisfied",
           personal_satis > 2 ~ "Not satisfied"
         ))

# Ideology

filtered_survey <- filtered_survey |> 
  mutate(ideology = if_else(d1 > 10, NA, d1)) 

# Contact LGBTQ+

filtered_survey <- filtered_survey %>% 
  mutate(contact_lgbti = case_when(
    sd1_4 == 1 | sd1_7 == 1 | sd1_8 == 1 ~ "Contact", # There is contact
    sd1_4 == 2 | sd1_7 == 2 | sd1_8 == 2 ~ "No contact", # There is not contact
    TRUE ~ NA
  ),
  contact_lgbti = factor(contact_lgbti))

# Autoperception of the social class

filtered_survey <- filtered_survey %>% 
  mutate(social_class = case_when(
    d63 %in% c(1, 2) ~ "Working class", 
    d63 == 3 ~ "Middle class", 
    d63 %in% c(4, 5) ~ "High class", 
    TRUE ~ NA
  )) #porque esta distribución???? pq en principio 2 y 4 es lower en higher middle class segun la encuesta

# Country names: DE-E and DE-W were problems 

filtered_survey <- filtered_survey %>% 
  mutate(country = country_name(isocntry, to = "simple", 
                                verbose = TRUE, poor_matches = TRUE),
         isocntry = countrycode::countrycode(country, origin = "country.name",
                                                destination = "iso2c"))
  
individual_data <- filtered_survey |> 
  select(caseid, isocntry, trans_name, female, age, religion, 
         marital_status, personal_satis, ideology, 
         contact_lgbti, social_class, occupation)
```



```{r}
#Merge

final_data <- individual_data |> 
  left_join(rainbow, by = c("isocntry" = "country_iso")) |> 
  left_join(trans, by = c("isocntry" = "country_iso")) |> 
  left_join(economic_indicators, by = c("isocntry" = "country_iso")) |> 
  left_join(religiosity, by = c("isocntry" = "country_iso"))
```



### Other variables that I have added

```{r}

# Difficulties to pay your bills

other_variables <- survey |> 
  mutate(bills = case_when(
    d60 == 1 ~ "Most of the time",
    d60 == 2 ~ "From time to time",
    d60 == 3 ~ "Almost never/ never",
    TRUE ~ NA
    ))
         
# How comfortable you would feel if one of your children was in love with a trans person

other_variables <- other_variables |> 
  mutate(child_love = if_else(qc13_11 > 10, NA, qc13_11))

# Trans in a high political position

other_variables <- other_variables |>  
  mutate(trans_pol = if_else(qc6_10 > 10, NA, qc6_10))

# Information in schools about being transgender 

other_variables <- other_variables |> 
  mutate(trans_school = case_when(
    qc17_4 == 1 ~ "Totally agree",
    qc17_4 == 2 ~ "Tend to agree",
    qc17_4 == 3 ~ "Tend to disagree",
    qc17_4 == 4 ~ "Totally disagree",
    TRUE ~ NA),
    trans_school = factor(trans_school))

other_variables <- other_variables |> 
  mutate(country = country_name(isocntry, to = "simple", 
                                verbose = TRUE, poor_matches = TRUE),
         isocntry = countrycode::countrycode(country, origin = "country.name",
                                                destination = "iso2c"))
  
other_variables <- other_variables |> 
  select(bills, child_love, trans_pol, trans_school, isocntry)

```

## Individual descriptive analysis
```{r}
library(DataExplorer)
library(ggplot2)
```


```{r}
plot_intro(final_data)
```


```{r}
str(final_data)
```

```{r}
summary(final_data)
```


```{r}
table(final_data$trans_name, final_data$female)
```

### Categorical variables

Distribution of the categorical variables in all the dataset

```{r}
font_add_google("Voces", "voces")
showtext_auto()

# Religion
g1 <- ggplot(final_data, aes(x = religion)) +
  geom_bar(aes(y = ..prop.., group = 1), fill = "#9C9EDE", color = "black") +
  scale_y_continuous(labels = percent_format()) +
  labs(title = "Religious identification", x = "Religion", y = "Percentage") +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    axis.title = element_text(size = 12, face = "bold")) +
  theme_minimal()

# Marital status
g2 <- ggplot(final_data, aes(x = marital_status)) +
  geom_bar(aes(y = ..prop.., group = 1), fill = "#98DF8A", color = "black") +
  scale_y_continuous(labels = percent_format()) +
  labs(title = "Marital status distribution", x = "Status", y = "Percentage") +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    axis.title = element_text(size = 12, face = "bold")) +
  theme_minimal()

# Personal satisfaction
g3 <- ggplot(final_data, aes(x = personal_satis)) +
  geom_bar(aes(y = ..prop.., group = 1), fill = "#FF9896", color = "black") +
  scale_y_continuous(labels = percent_format()) +
  labs(title = "Personal Satisfaction", 
       x = "Response", y = "Percentage") +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    axis.title = element_text(size = 12, face = "bold")) +
  theme_minimal()

# Social class
g4 <- ggplot(final_data, aes(x = social_class)) +
  geom_bar(aes(y = ..prop.., group = 1), fill = "#9EDAE5", color = "black") +
  scale_y_continuous(labels = percent_format()) +
  labs(title = "Self-reported social slass", x = "Social class", y = "Percentage") +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    axis.title = element_text(size = 12, face = "bold")) +
  theme_minimal()

#Occupation

g5 <- ggplot(final_data, aes(x = occupation)) +
  geom_bar(aes(y = ..prop.., group = 1), fill = "yellow", color = "black") +
  scale_y_continuous(labels = percent_format()) +
  labs(title = "Occupation distribution", x = "Occupation", y = "Percentage") +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    axis.title = element_text(size = 12, face = "bold")) +
  theme_minimal()

# Contact with LGTB community

g6 <- ggplot(final_data, aes(x = contact_lgbti)) +
  geom_bar(aes(y = ..prop.., group = 1), fill = "darkblue", color = "black") +
  scale_y_continuous(labels = percent_format()) +
  labs(title = "Contact with the LGTBI community", x = "Response", y = "Percentage") +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    axis.title = element_text(size = 12, face = "bold")) +
  theme_minimal()

# Graphs combined
g <- (g1 | g2 | g3) / (g4 | g5 | g6) 
g

```
```{r}
ggplot(final_data, aes(x = age)) +
  geom_histogram(aes(y = ..density..), bins = 30, fill = "steelblue", alpha = 0.6) +
  geom_density(color = "red", size = 1) +
  theme_minimal() +
  labs(title = "Age Distribution", x = "Age", y = "Density")

```
### Variable Distribution by Country




```{r}

#seleccionamos variables numericas y a nivel país
corr_data <- final_data |> 
  select(trans_name, age, ideology, rain_ind, gini, gdp_pc, religiosity_percent)

corr_matrix <- cor(corr_data, use = "complete.obs")

plot_correlation(corr_matrix)

```




### Questions related with trans people

```{r}

# Boxplot 1: trans_child
b1 <- ggplot(other_variables, 
             aes(x = reorder(isocntry, child_love, FUN = median, decreasing = TRUE), 
                                  y = child_love)) +
  geom_boxplot(fill = "#FFBB78", outlier.colour = "red", outlier.fill = "red") +
  labs(title = "How comfortable would you feel if one of your children was in love with a trans person?", 
       x = "Country", y = "Support Level") +
  theme(
    axis.text.x = element_text(angle = 0, hjust = 1),
    axis.title = element_text(size = 12, face = "bold")) +
  theme_minimal()


# Boxplot 2: trans_pol
b2 <- ggplot(other_variables, 
             aes(x = reorder(isocntry, trans_pol, FUN = median, decreasing = TRUE), 
                                  y = trans_pol)) +
  geom_boxplot(fill = "#AEC7E8", outlier.colour = "red", outlier.fill = "red") +
  labs(title = "Trans people in high political positions", 
       x = "Country", y = "Support Level") +
  theme(
    axis.text.x = element_text(angle = 0, hjust = 1),
    axis.title = element_text(size = 12, face = "bold")) +
  theme_minimal()

# Boxplots combined
b <- b1 / b2 
b

```



### Mice imputation for ideology

```{r}
colSums(is.na(individual_data))

individual_data <- individual_data %>%
  mutate(across(where(is.labelled), as_factor))

# Revisar las clases de las variables para asegurar la conversión
str(individual_data)

# Definir los métodos de imputación para cada variable
methods <- make.method(individual_data)

# Asignar métodos específicos a cada variable
methods["ideology"] <- "norm.boot"     # Para variable continua
methods["trans_name"] <- "pmm"         # Método pmm para variable continua o ordinal
methods["religion"] <- "polyreg"       # Imputación para variables categóricas
methods["marital_status"] <- "polyreg"
methods["occupation"] <- "polyreg"
methods["trans_school"] <- "polyreg"

# Realizar la imputación con métodos específicos
imputed_data <- mice(individual_data, m = 10, method = methods, seed = 123)

# Crear el dataframe con los diferentes métodos de imputación para 'ideology'
data_imputed <- data.frame(
  trans_name = individual_data$trans_name,
  original = individual_data$ideology,
  imputed_median = replace(individual_data$ideology, 
                           is.na(individual_data$ideology), 
                           median(individual_data$ideology, na.rm = TRUE)),
  imputed_normboot = complete(imputed_data)$ideology,
  imputed_pmm = complete(mice(individual_data, m = 10, 
                              method = "pmm", seed = 123))$ideology,
  imputed_rf = complete(mice(individual_data, m = 10, 
                             method = "rf", seed = 123))$ideology
)
```

